{
 "title": "Infinispan / DataGrid",
 "description": "Infinispan/DataGrid Prometheus Exporter Dashboard",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cache",
    "label": "cache",
    "query": "label_values(datagrid_cache, name)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Content  for \"$cache\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "env"
  },
  {
   "title": "# Entries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(datagrid_cluster_cache_stats{attribute=\"number_of_entries\", name=\"$cache\"})"
    }
   ]
  },
  {
   "title": "# Replicas",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(datagrid_cache_stats{attribute=\"number_of_entries\", name=\"$cache\"})"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(datagrid_cluster_cache_stats{attribute=\"read_write_ratio\",name=\"$cache\"})",
     "legendFormat": "READ/WRITE RATIO"
    },
    {
     "expr": "sum(datagrid_cluster_cache_stats{attribute=\"hit_ratio\",name=\"$cache\"})",
     "legendFormat": "HIT RATIO"
    }
   ]
  },
  {
   "title": "Operations for \"$cache\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "env"
  },
  {
   "title": "Operations Performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"average_read_time_nanos\"})",
     "legendFormat": "AVERAGE READ TIME"
    },
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"average_write_time_nanos\"})",
     "legendFormat": "AVERAGE WRITE TIME"
    },
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"average_remove_time_nanos\"})",
     "legendFormat": "AVERAGE REMOVE TIME"
    }
   ]
  },
  {
   "title": "Caching Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"hits\"})",
     "legendFormat": "READ Hits"
    },
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"misses\"})",
     "legendFormat": "READ Misses"
    },
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"remove_hits\"})",
     "legendFormat": "REMOVE Hits"
    },
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"remove_misses\"})",
     "legendFormat": "REMOVE Misses"
    },
    {
     "expr": "avg(datagrid_cluster_cache_stats{name=\"$cache\",attribute=\"stores\"})",
     "legendFormat": "PUTS"
    }
   ]
  },
  {
   "title": "Nodes for \"$cache\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Entries Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "datagrid_cache_stats{attribute=\"number_of_entries\", name=\"$cache\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Average READ Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "datagrid_cache_stats{name=\"$cache\",attribute=\"average_read_time_nanos\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average WRITE Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "datagrid_cache_stats{name=\"$cache\",attribute=\"average_write_time_nanos\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total READs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "operations" }
   ],
   "targets": [
    {
     "expr": "datagrid_cache_stats{attribute=\"hits\",name=\"$cache\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed READs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "operations" }
   ],
   "targets": [
    {
     "expr": "datagrid_cache_stats{attribute=\"misses\",name=\"$cache\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total WRITEs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "operations" }
   ],
   "targets": [
    {
     "expr": "datagrid_cache_stats{attribute=\"stores\",name=\"$cache\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}